version: '3'
services:
  wordpress:
    image: wordpress:latest
    ports:
      - 8085:80
    volumes:
      - /Volumes/Extra/raju-home/Sites/PrayersConnect/wordpress-plugin/prayers-connect:/var/www/html/wp-content/plugins/prayers-connect
    environment:
      WORDPRESS_DB_HOST: api-mysql-1
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
      WORDPRESS_DB_NAME: wp-test
      # WORDPRESS_DEBUG: 1
    networks:
      - pcapi

networks:
  pcapi:
    external:
      name: api_pcapi
